#include "splat_constructor/ply_writer.hpp"

#include <array>
#include <bit>
#include <fstream>
#include <stdexcept>
#include <string>

namespace splat {
namespace {

void write_float(std::ostream& output, float value) {
    output.write(reinterpret_cast<const char*>(&value), sizeof(value));
}

const char* semantics_name(DepthSemantics semantics) {
    switch (semantics) {
    case DepthSemantics::RelativeInverse:
        return "relative_inverse";
    case DepthSemantics::MetricCameraZ:
        return "metric_camera_z";
    case DepthSemantics::PseudoInverseFromSegmentation:
        return "pseudo_inverse_from_segmentation";
    }
    return "unknown";
}

} // namespace

void write_3dgs_ply(const std::filesystem::path& path, const GaussianSet& gaussians) {
    gaussians.validate();
    if constexpr (std::endian::native != std::endian::little) {
        throw std::runtime_error("binary PLY output currently requires a little-endian host");
    }
    static_assert(sizeof(float) == 4, "3DGS PLY requires IEEE-style 32-bit floats");

    std::ofstream output(path, std::ios::binary);
    if (!output) {
        throw std::runtime_error("cannot open PLY output: " + path.string());
    }
    output << "ply\nformat binary_little_endian 1.0\n";
    output << "comment generated by Group 27 single-image Splat Constructor\n";
    output << "element vertex " << gaussians.size() << '\n';
    output << "property float x\nproperty float y\nproperty float z\n";
    output << "property float nx\nproperty float ny\nproperty float nz\n";
    output << "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n";
    for (int index = 0; index < 45; ++index) {
        output << "property float f_rest_" << index << '\n';
    }
    output << "property float opacity\n";
    output << "property float scale_0\nproperty float scale_1\nproperty float scale_2\n";
    output << "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n";
    output << "end_header\n";

    constexpr std::array<float, 45> zero_rest{};
    for (std::size_t index = 0; index < gaussians.size(); ++index) {
        for (std::size_t component = 0; component < 3; ++component) {
            write_float(output, gaussians.positions[index * 3 + component]);
        }
        write_float(output, 0.0F);
        write_float(output, 0.0F);
        write_float(output, 0.0F);
        for (std::size_t component = 0; component < 3; ++component) {
            write_float(output, gaussians.sh_dc[index * 3 + component]);
        }
        output.write(
            reinterpret_cast<const char*>(zero_rest.data()),
            static_cast<std::streamsize>(zero_rest.size() * sizeof(float))
        );
        write_float(output, gaussians.opacity_logits[index]);
        for (std::size_t component = 0; component < 3; ++component) {
            write_float(output, gaussians.log_scales[index * 3 + component]);
        }
        for (std::size_t component = 0; component < 4; ++component) {
            write_float(output, gaussians.rotations[index * 4 + component]);
        }
    }
    if (!output) {
        throw std::runtime_error("failed while writing PLY output: " + path.string());
    }
}

void write_construction_metadata(
    const std::filesystem::path& path,
    const GaussianSet& gaussians,
    const CameraIntrinsics& intrinsics,
    const ConstructionConfig& config,
    std::size_t width,
    std::size_t height
) {
    std::ofstream output(path);
    if (!output) {
        throw std::runtime_error("cannot open metadata output: " + path.string());
    }
    output << "{\n"
           << "  \"schema_version\": 1,\n"
           << "  \"gaussian_count\": " << gaussians.size() << ",\n"
           << "  \"source_resolution\": [" << width << ", " << height << "],\n"
           << "  \"depth_semantics\": \"" << semantics_name(config.depth_semantics) << "\",\n"
           << "  \"depth_units\": \"unitless\",\n"
           << "  \"near_depth\": " << config.near_depth << ",\n"
           << "  \"far_depth\": " << config.far_depth << ",\n"
           << "  \"sample_stride\": " << config.sample_stride << ",\n"
           << "  \"intrinsics\": {\n"
           << "    \"fx\": " << intrinsics.fx << ", \"fy\": " << intrinsics.fy
           << ", \"cx\": " << intrinsics.cx << ", \"cy\": " << intrinsics.cy << "\n"
           << "  },\n"
           << "  \"coordinate_system\": {\n"
           << "    \"handedness\": \"right_handed\",\n"
           << "    \"x\": \"right\", \"y\": \"up\", \"z\": \"backward\",\n"
           << "    \"camera_forward\": \"negative_z\"\n"
           << "  }\n"
           << "}\n";
}

} // namespace splat
