#include "splat_constructor/ply_writer.hpp"

#include <array>
#include <atomic>
#include <bit>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <locale>
#include <cmath>
#include <stdexcept>
#include <string>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#endif

namespace splat {
namespace {

void write_float(std::ostream& output, float value) {
    output.write(reinterpret_cast<const char*>(&value), sizeof(value));
}

std::filesystem::path temporary_path_for(const std::filesystem::path& destination) {
    static std::atomic<std::uint64_t> sequence{};
    const auto ticks = std::chrono::steady_clock::now().time_since_epoch().count();
    return destination.parent_path()
        / (destination.filename().string() + ".tmp-" + std::to_string(ticks) + "-"
           + std::to_string(sequence.fetch_add(1)));
}

void commit_temporary_file(
    const std::filesystem::path& temporary,
    const std::filesystem::path& destination
) {
#ifdef _WIN32
    if (MoveFileExW(
            temporary.c_str(),
            destination.c_str(),
            MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH
        ) == 0) {
        const auto error = GetLastError();
        throw std::runtime_error(
            "cannot commit output atomically (Windows error " + std::to_string(error) + "): "
            + destination.string()
        );
    }
#else
    std::error_code error;
    std::filesystem::rename(temporary, destination, error);
    if (error) {
        throw std::runtime_error(
            "cannot commit output atomically: " + destination.string() + ": " + error.message()
        );
    }
#endif
}

template <typename Writer>
void write_atomically(
    const std::filesystem::path& destination,
    std::ios::openmode mode,
    Writer writer
) {
    const auto temporary = temporary_path_for(destination);
    try {
        std::ofstream output(temporary, mode);
        if (!output) {
            throw std::runtime_error("cannot open temporary output: " + temporary.string());
        }
        output.imbue(std::locale::classic());
        writer(output);
        output.flush();
        if (!output) {
            throw std::runtime_error("failed while writing output: " + destination.string());
        }
        output.close();
        if (!output) {
            throw std::runtime_error("failed while closing output: " + destination.string());
        }
        commit_temporary_file(temporary, destination);
    } catch (...) {
        std::error_code ignored;
        std::filesystem::remove(temporary, ignored);
        throw;
    }
}

const char* semantics_name(DepthSemantics semantics) {
    switch (semantics) {
    case DepthSemantics::RelativeInverse:
        return "relative_inverse";
    case DepthSemantics::MetricCameraZ:
        return "metric_camera_z";
    case DepthSemantics::PseudoInverseFromSegmentation:
        return "pseudo_inverse_from_segmentation";
    }
    throw std::invalid_argument("unknown depth semantics");
}

} // namespace

void write_3dgs_ply(const std::filesystem::path& path, const GaussianSet& gaussians) {
    gaussians.validate();
    if constexpr (std::endian::native != std::endian::little) {
        throw std::runtime_error("binary PLY output currently requires a little-endian host");
    }
    static_assert(sizeof(float) == 4, "3DGS PLY requires IEEE-style 32-bit floats");

    write_atomically(path, std::ios::binary, [&gaussians](std::ostream& output) {
        output << "ply\nformat binary_little_endian 1.0\n";
        output << "comment generated by Group 27 single-image Splat Constructor\n";
        output << "element vertex " << gaussians.size() << '\n';
        output << "property float x\nproperty float y\nproperty float z\n";
        output << "property float nx\nproperty float ny\nproperty float nz\n";
        output << "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n";
        for (int index = 0; index < 45; ++index) {
            output << "property float f_rest_" << index << '\n';
        }
        output << "property float opacity\n";
        output << "property float scale_0\nproperty float scale_1\nproperty float scale_2\n";
        output << "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n";
        output << "end_header\n";

        constexpr std::array<float, 45> zero_rest{};
        for (std::size_t index = 0; index < gaussians.size(); ++index) {
            for (std::size_t component = 0; component < 3; ++component) {
                write_float(output, gaussians.positions[index * 3 + component]);
            }
            write_float(output, 0.0F);
            write_float(output, 0.0F);
            write_float(output, 0.0F);
            for (std::size_t component = 0; component < 3; ++component) {
                write_float(output, gaussians.sh_dc[index * 3 + component]);
            }
            output.write(
                reinterpret_cast<const char*>(zero_rest.data()),
                static_cast<std::streamsize>(zero_rest.size() * sizeof(float))
            );
            write_float(output, gaussians.opacity_logits[index]);
            for (std::size_t component = 0; component < 3; ++component) {
                write_float(output, gaussians.log_scales[index * 3 + component]);
            }
            for (std::size_t component = 0; component < 4; ++component) {
                write_float(output, gaussians.rotations[index * 4 + component]);
            }
        }
    });
}

void write_construction_metadata(
    const std::filesystem::path& path,
    const GaussianSet& gaussians,
    const CameraIntrinsics& intrinsics,
    const ConstructionConfig& config,
    std::size_t width,
    std::size_t height,
    float horizontal_fov_degrees
) {
    gaussians.validate();
    if (width == 0 || height == 0 || !(intrinsics.fx > 0.0F) || !(intrinsics.fy > 0.0F)
        || !std::isfinite(intrinsics.cx) || !std::isfinite(intrinsics.cy)
        || !(horizontal_fov_degrees > 0.0F) || !(horizontal_fov_degrees < 180.0F)
        || !(config.near_depth > 0.0F) || !(config.far_depth > config.near_depth)
        || !(config.opacity > 0.0F && config.opacity < 1.0F)
        || !(config.scale_multiplier > 0.0F) || !(config.thickness_multiplier > 0.0F)
        || !std::isfinite(config.depth_edge_threshold) || config.depth_edge_threshold < 0.0F
        || !(config.edge_scale_multiplier > 0.0F && config.edge_scale_multiplier <= 1.0F)
        || !std::isfinite(config.minimum_reconstruction_weight)
        || config.minimum_reconstruction_weight < 0.0F
        || config.minimum_reconstruction_weight >= 1.0F) {
        throw std::invalid_argument("invalid construction metadata values");
    }
    const char* depth_units = config.depth_semantics == DepthSemantics::MetricCameraZ
        ? "meters" : "unitless";
    write_atomically(path, std::ios::out, [&](std::ostream& output) {
        output << "{\n"
           << "  \"schema_version\": 1,\n"
           << "  \"gaussian_count\": " << gaussians.size() << ",\n"
           << "  \"source_resolution\": [" << width << ", " << height << "],\n"
           << "  \"depth_semantics\": \"" << semantics_name(config.depth_semantics) << "\",\n"
           << "  \"depth_units\": \"" << depth_units << "\",\n"
           << "  \"near_depth\": " << config.near_depth << ",\n"
           << "  \"far_depth\": " << config.far_depth << ",\n"
           << "  \"sample_stride\": " << config.sample_stride << ",\n"
           << "  \"mask_threshold\": " << static_cast<unsigned>(config.mask_threshold) << ",\n"
           << "  \"opacity\": " << config.opacity << ",\n"
           << "  \"scale_multiplier\": " << config.scale_multiplier << ",\n"
           << "  \"thickness_multiplier\": " << config.thickness_multiplier << ",\n"
           << "  \"depth_edge_threshold\": " << config.depth_edge_threshold << ",\n"
           << "  \"edge_scale_multiplier\": " << config.edge_scale_multiplier << ",\n"
           << "  \"minimum_reconstruction_weight\": "
           << config.minimum_reconstruction_weight << ",\n"
           << "  \"horizontal_fov_degrees\": " << horizontal_fov_degrees << ",\n"
           << "  \"intrinsics\": {\n"
           << "    \"fx\": " << intrinsics.fx << ", \"fy\": " << intrinsics.fy
           << ", \"cx\": " << intrinsics.cx << ", \"cy\": " << intrinsics.cy << "\n"
           << "  },\n"
           << "  \"coordinate_system\": {\n"
           << "    \"handedness\": \"right_handed\",\n"
           << "    \"x\": \"right\", \"y\": \"up\", \"z\": \"backward\",\n"
           << "    \"camera_forward\": \"negative_z\"\n"
           << "  }\n"
           << "}\n";
    });
}

} // namespace splat
